apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: bp3ejrz58-nodejs
  janus-idp.io/tekton: bp3ejrz58-nodejs
  backstage.io/kubernetes-id: bp3ejrz58-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bp3ejrz58-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
